authors:
  greg:
    name: Greg Malewski
    description: SAP UI5 developer and architect
    avatar: https://avatars.githubusercontent.com/u/11041095
    url: https://github.com/squidfunk
  alexvoss:
    name: Alex Voss
    description: Community support
    avatar: https://avatars.githubusercontent.com/u/4134224
    url: https://github.com/alexvoss