authors:
  greg:
    name: Greg Malewski
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/11041095
    url: https://github.com/gmalew
  nype:
    name: Nype
    description: Company
    avatar: https://avatars.githubusercontent.com/u/57181796
    url: https://github.com/nypesap