name: ci 
on:
  push:
    branches:
      - master 
      - main
  workflow_dispatch: {}
  repository_dispatch:
    types: [theme-dispatch]
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  deploy:
    uses: nypesap/mkdocs-nype/.github/workflows/reusable_deploy.yml@main
    secrets:
      INPUT_ENV: ${{ vars.INPUT_ENV }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_PORT: ${{ secrets.SSH_PORT }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_TARGET: ${{ secrets.SSH_TARGET }}
      SSH_COMMAND: ${{ secrets.SSH_COMMAND }}
