name: ci 
on:
  push:
    branches:
      - master 
      - main
      - test-ci
env:
  CI: true
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: mkdir -p .cache; echo mkdocs-material > .cache/safe
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ hashfiles('.cache/**') }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install -r requirements.txt
      - run: mkdocs build --strict
      - name: Prepare deploy archive
        run: |
          zip -r site.zip site/
          sha256sum site.zip > checksum
          sha256sum -c checksum
          mkdir -p deploy
          zip deploy/deploy.zip site.zip checksum
      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          protocol: ftps
          server: ${{ secrets.FTP_HOST }}
          port: ${{ secrets.FTP_PORT }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          local-dir: deploy/
          server-dir: ${{ secrets.FTP_DIR }}
      - name: Confirm deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        env:
          FTP_DIR: ${{ secrets.FTP_DIR }}
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          envs: FTP_DIR
          script: ${{ secrets.SSH_COMMAND }}
          script_stop: true
          command_timeout: 30s